name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $GITHUB_ENV

      # Step 4: Install dependencies using Bun
      - name: Install dependencies
        run: bun install

      # Step 5: Install Playwright dependencies
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Step 6: Run Playwright tests using Bun (Chromium only)
      - name: Run Playwright E2E tests (Chromium)
        run: bun playwright test --project=chromium

      # Step 7: Upload screenshots and videos if tests fail
      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: tests/screenshots
