name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $GITHUB_ENV
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Step 4: Validate Bun installation
      - name: Validate Bun Installation
        run: bun --version

      # Step 5: Cache Bun dependencies
      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Step 6: Install dependencies using Bun
      - name: Install dependencies
        run: bun install

      # Step 7: Install Playwright (Using npx)
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Step 8: Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # Step 9: Start Next.js server
      - name: Start Next.js server
        run: NEXT_PUBLIC_API_BASE_URL=http://localhost:8000 bun run dev &
        env:
          NODE_ENV: development

      # Step 10: Wait for Next.js server to be ready
      - name: Wait for Next.js server
        run: sleep 10

      # Step 11: Run Playwright tests (Chromium only)
      - name: Run Playwright E2E tests (Chromium)
        run: bun run test:e2e

      # Step 12: Upload screenshots and videos if tests fail
      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: tests/screenshots/
